name: "CI/CD Pipeline"

on:
  push:
    branches: [test, uat, main]
  pull_request:
    branches: [test, uat, main]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  security-events: write
  pull-requests: write
  id-token: write

concurrency:
  group: cicd-backend-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

jobs:
  pipeline:
    uses: Tone-Lloyd-Sir-Catubag-CICD/cicd-workflow/.github/workflows/master-pipeline-be.yml@v1
    with:
      pipeline_mode: single
      enable_security_scan: true
      enable_sonar: false
      enable_k6: false
      k6_script_path: "tests/performance"
      k6_base_url: ""
      k6_run_only_on_branch: "test,main"
      run_deploy: false
      run_promotion: false
      dry_run: false
    secrets: inherit
